name: Deploy Frontend
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t mhdikmen1/docker-frontend-1 -f Dockerfile.dev .
      - run: docker run -e CI=true mhdikmen1/docker-frontend-1 npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: "docker-frontend-1"
          environment_name: "Docker-frontend-1-env"
          existing_bucket_name: elasticbeanstalk-us-east-1-590183657956
          region: "us-east-1"
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
